CREATE TABLE User (
	UserID VARCHAR(50) NOT NULL,
	Rating INTEGER NOT NULL,
	Location VARCHAR(50),
	Country VARCHAR(50),
	PRIMARY KEY(UserID)
) ENGINE=InnoDB;

CREATE TABLE Item (
	ItemID INTEGER NOT NULL,
	Name VARCHAR(100) NOT NULL,
	Description VARCHAR(4000),
	Currently DECIMAL(8,2) NOT NULL,
	Buy_Price DECIMAL(8,2) DEFAULT NULL,
	First_Bid DECIMAL(8,2) NOT NULL,
	Number_of_bids INTEGER NOT NULL,
	SellerID VARCHAR(50) NOT NULL,
	Started TIMESTAMP NOT NULL,
	Ends TIMESTAMP NOT NULL,
	PRIMARY KEY(ItemID),
	FOREIGN KEY(SellerID) REFERENCES User(UserID)
) ENGINE=InnoDB;

CREATE TABLE Locate (
	ItemID INTEGER NOT NULL,
	Location VARCHAR(50) NOT NULL,
	Country VARCHAR(50) NOT NULL,
	Latitude DECIMAL(9,6) DEFAULT NULL,
	Longitude DECIMAL(9,6) DEFAULT NULL,
	PRIMARY KEY(ItemID),
	FOREIGN KEY(ItemID) REFERENCES Item(ItemID)
) ENGINE=InnoDB;

CREATE TABLE Bids (
	ItemID INTEGER NOT NULL,
	BuyerID VARCHAR(50) NOT NULL,
	Time TIMESTAMP NOT NULL,
	Amount DECIMAL(8,2) NOT NULL,
	PRIMARY KEY(BuyerID, Time),
	FOREIGN KEY(BuyerID) REFERENCES User(UserID),
	FOREIGN KEY(ItemID) REFERENCES Item(ItemID)	
) ENGINE=InnoDB;

CREATE TABLE Category (
	CategoryID INTEGER NOT NULL,
	CategoryName VARCHAR(100) NOT NULL,
	PRIMARY KEY(CategoryID)
) ENGINE=InnoDB;

CREATE TABLE ItemCategory (
	ItemID INTEGER NOT NULL,
	CategoryID INTEGER NOT NULL,
	PRIMARY KEY(ItemID, CategoryID),
	FOREIGN KEY(ItemID) REFERENCES Item(ItemID),
	FOREIGN KEY(CategoryID) REFERENCES Category(CategoryID)
) ENGINE=InnoDB;
